Repository Camp-SAMI/campsight, pull requests merged in 2018-10, with the labels that each got.

#30 Landing page #22
  client/components/LandingPage.js
  client/components/index.js
  client/routes.js
  package-lock.json
  package.json
  public/image1.jpg
  public/style.css
  public/white_logo_transparent_background.png
Labels: in progress

#31 Reservation form #21
  client/components/DatePicker.js
  client/components/ReservationForm.js
  client/components/index.js
  client/routes.js
  client/store/reservation.js
  package-lock.json
  package.json
  public/index.html
  server/db/models/camper.js
  server/db/models/campsite.js
Labels: in progress

#32 Campsite detail issue#28
  client/components/CampsiteCollection.js
  client/components/LandingPage.js
  client/components/MapView.js
  client/components/index.js
  client/routes.js
  package-lock.json
  package.json
  public/style.css
  server/api/campsites.js
  server/api/index.js
  server/api/reservations.js
  server/index.js
Labels: in progress, needs review

#35 Seed #10
  campSiteSeedData.js
  campsite.md
  package-lock.json
  package.json
  public/images/BetterSingleCabin.jpg
  public/images/BetterTent.jpg
  public/images/SingleCamperStock.jpg
  script/seed.js
  seed.js
  server/db/models/amenity.js
  server/db/models/campground.js
  server/db/models/campsiteAmenities.js
  server/db/models/campsiteReservations.js
  server/db/models/index.js
  testSeedPractice.js
Labels: in progress

#36 Campsite detail issue#28
  client/components/CampsiteCollection.js
  client/components/LandingPage.js
  client/store/filteredCampsites.js
  client/store/index.js
  package-lock.json
  package.json
  server/api/campsites.js
Labels: in progress

#37 corrected the seed data
  campSiteSeedData.js
  client/components/CampsiteBlock.js
  public/BetterSingleCabin.jpg
  public/BetterTent.jpg
  public/SingleCamperStock.jpg
Labels: in progress

#38 Seed #10
  client/components/CampsiteCollection.js
  client/components/MapView.js
  public/camperIcon.png
Labels: in progress

#41 Semantic #34
  campSiteSeedData.js
  client/components/Amenities.js
  client/components/CampsiteBlock.js
  client/components/CampsiteCollection.js
  client/components/LandingPage.js
  client/components/NewNavbar.js
  client/components/Type.js
  client/components/navbar.js
  package-lock.json
  package.json
  public/index.html
  public/style.css
Labels: needs review

#44 Campsite detail issue#28
  campSiteSeedData.js
  client/components/Amenities.js
  client/components/CampsiteCollection.js
  client/components/DatePicker.js
  client/components/EndDatePicker.js
  client/components/LandingPage.js
  client/components/Submenu.js
  client/components/Type.js
  client/components/navbar.js
  client/store/amenities.js
  client/store/filteredCampsites.js
  package-lock.json
  package.json
  script/seed.js
  server/db/models/reservation.js
Labels: in progress

#58 Campsite detail issue#28
  client/components/CampsiteBlock.js
  client/components/CampsiteCollection.js
  client/components/CampsiteDetail.js
  client/components/DatePicker.js
  client/components/EndDatePicker.js
  client/components/LandingPage.js
  client/components/MapView.js
  client/routes.js
  client/store/campsite.js
  server/api/reservations.js
Labels: needs review

#59 Ticket model #45
  client/components/MapView.js
  package-lock.json
  script/seed.js
  server/db/models/index.js
  server/db/models/ticket.js
Labels: in progress

#61 Campsite reservation and payment #55
  client/components/CampsiteDetail.js
  client/components/Checkout.js
  client/components/MapView.js
  client/components/ReservationForm.js
  client/utils/formatPrice.js
  package-lock.json
  package.json
  server/db/models/campsite.js
  server/db/models/reservation.js
  server/utils/formatPrice.js
  server/utils/getSha1.js
Labels: in progress

#64 Campsite reservation and payment #55
  client/components/CampsiteDetail.js
  client/components/Checkout.js
  client/components/ReservationForm.js
  package-lock.json
  server/api/reservations.js
Labels: in progress

#66 Ticket components issue#60
  client/components/AdminCampsites.js
  client/components/EditCampsite.js
  client/store/campsites.js
  client/store/index.js
  client/store/ticket.js
  client/store/tickets.js
  server/api/index.js
  server/api/tickets.js
Labels: in progress

#74 Admincamperslist #65
  client/components/Camper.js
  client/components/CamperRow.js
  client/components/CampersList.js
  client/components/index.js
  client/routes.js
  client/store/camper.js
  client/store/campers.js
  client/store/index.js
  server/api/campers.js
  server/api/reservations.js
  server/index.js
Labels: in progress

#76 data to make tickets for the seed is made.
  ticketSeedData.js
Labels: in progress

#77 data to make tickets for the seed is made.
  ticketSeedData.js
Labels: in progress

#75 Admin sidebar #51
  client/components/AdminSidebar.js
  client/components/Reservations.js
  client/components/SingleReservation.js
  client/components/navbar.js
  server/api/reservations.js
  server/db/models/reservation.js
Labels: in progress

#78 Ticket components issue#60
  client/components/AdminSidebar.js
  client/components/ClosedTicketTable.js
  client/components/OpenTicketTable.js
  client/components/TicketList.js
  client/components/UnassignedTicketTable.js
  client/components/index.js
  client/routes.js
  client/store/index.js
  package-lock.json
  package.json
  server/api/tickets.js
Labels: needs review

#79 Admin sidebar #51
  client/components/AdminSidebar.js
  client/components/CampsiteBlock.js
  client/components/ReservationRow.js
  client/components/Reservations.js
  client/components/SingleReservation.js
  client/components/index.js
  client/components/navbar.js
  client/routes.js
  client/store/reservation.js
  client/store/reservations.js
  public/image4.png
  public/style.css
  server/api/reservations.js
Labels: needs review

#84 Admin campsites issue#53
  client/components/AddCampsite.js
  client/components/AdminCampsites.js
  client/components/AdminSingleCampsite.js
  client/components/CampsiteRow.js
  client/components/ClosedTicketTable.js
  client/components/EditTicket.js
  client/components/OpenTicketTable.js
  client/components/TicketList.js
  client/components/UnassignedTicketTable.js
  client/components/index.js
  client/routes.js
  client/store/campsite.js
  client/store/campsites.js
  client/utils/locationConverter.js
  package-lock.json
  package.json
  server/api/campsites.js
  server/api/tickets.js
Labels: needs review

#85 some styles, not done
  client/components/CampsiteBlock.js
  client/components/CampsiteCollection.js
  client/components/DatePicker.js
  client/components/LandingPage.js
  client/components/Submenu.js
  client/components/navbar.js
  public/style.css
Labels: in progress

#86 Admin campsites issue#53
  client/components/AddCampsite.js
  client/components/AdminCampsites.js
  client/components/CampsiteRow.js
  client/components/ClosedTicketTable.js
  client/components/EditCampsite.js
  client/components/ReservationRow.js
  client/store/campsite.js
  server/api/campsites.js
Labels: in progress

#87 Ticket form #46
  client/components/AdminDashboard.js
  client/components/Camera.js
  client/components/ClosedTicketTable.js
  client/components/EditTicket.js
  client/components/LandingPage.js
  client/components/OpenTicketTable.js
  client/components/Submenu.js
  client/components/TicketForm.js
  client/components/TicketFormContainer.js
  client/components/UnassignedTicketTable.js
  client/components/index.js
  client/routes.js
  client/store/index.js
  client/store/ticket.js
  client/store/ticketFormContainer.js
  package-lock.json
  package.json
  public/style.css
  server/api/tickets.js
  server/db/models/ticket.js
Labels: in progress

#89 unlocked routes temporarily
  server/api/campers.js
Labels: in progress

#90 Admincamperslist #65
  client/components/AdminSidebar.js
  client/components/Camper.js
  client/components/CamperProfile.js
  client/components/CamperRow.js
  client/components/CampersList.js
  client/components/CampersSearchBar.js
  client/components/CampsiteDetail.js
  client/components/Checkout.js
  client/components/Reservations.js
  client/components/SingleReservation.js
  client/components/index.js
  client/routes.js
  client/store/camper.js
  client/store/index.js
  client/store/reservations.js
  client/store/tickets.js
  package-lock.json
  package.json
  server/api/campers.js
  server/api/tickets.js
  server/db/models/user.js
Labels: needs review

#91 Ticket form #46
  client/components/EditTicket.js
  client/components/TicketList.js
  client/components/navbar.js
Labels: in progress

#104 Ticket form #46
  client/components/EditTicket.js
  client/components/HelpSubSuccess.js
  client/components/TicketForm.js
  client/components/index.js
Labels: needs review

#105 Edit tickets issue#91
  client/components/EditTicket.js
  client/components/TicketList.js
  client/components/TicketRow.js
  client/components/TicketTable.js
  client/components/index.js
  client/store/filteredCampsites.js
Labels: in progress

#106 Edit tickets issue#91
  client/components/AdminCampsites.js
  client/components/AdminSidebar.js
  client/components/CampsiteRow.js
  client/components/EditCampsite.js
  client/components/EditTicket.js
  client/components/TicketForm.js
  client/components/TicketList.js
  client/components/TicketRow.js
  client/components/TicketTable.js
  client/store/tickets.js
  server/api/campsites.js
  server/api/tickets.js
Labels: needs review

#107 Bigger reserve button #101
  client/components/AdminDashboard.js
  client/components/AdminSidebar.js
  client/components/Checkout.js
  client/components/ReservationForm.js
  client/components/index.js
  client/components/navbar.js
  client/components/user-home.js
  client/routes.js
  client/store/campsites.js
Labels: needs review

#110 Insights issue#107
  client/components/ClosedTicketTable.js
  client/components/Insights.js
  client/components/OpenTicketTable.js
  client/components/TicketList.js
  client/components/UnassignedTicketTable.js
  client/components/index.js
  client/routes.js
  client/store/filteredCampsites.js
  script/seed.js
  server/db/models/index.js
Labels: in progress

#111 Styles #82
  client/components/CampsiteCollection.js
  client/components/Checkout.js
  client/components/Itinerary.js
  client/components/Submenu.js
  client/components/index.js
  client/routes.js
  client/store/index.js
  client/store/itinerary.js
  client/store/ticket.js
  public/style.css
Labels: in progress

#115 Bigger reserve button #101
  client/components/CampsiteCollection.js
  client/components/LandingPage.js
  package-lock.json
  package.json
  public/index.html
Labels: in progress

#116 Add images #94
  campSiteSeedData.js
  client/components/HelpSubSuccess.js
  client/components/TicketForm.js
  client/components/navbar.js
  client/store/amenities.js
  public/style.css
  server/api/amenities.js
Labels: needs review

#118 Navbar fix #117
  client/components/navbar.js
  public/index.html
  script/seed.js
Labels: in progress

#119 Final styles #114
  client/components/Amenities.js
  client/components/CampsiteBlock.js
  client/components/CampsiteCollection.js
  client/components/DatePicker.js
  client/components/MapView.js
  client/components/Submenu.js
  client/components/navbar.js
  public/image1.jpg
  public/image4.png
  public/image5.jpg
  public/image6.jpg
  public/index.html
  public/style.css
Labels: in progress

#120 Fix calendar bugs #93
  client/components/AddCampsite.js
  client/components/CamperProfile.js
  client/components/CampsiteCollection.js
  client/components/CampsiteDetail.js
  client/components/EditTicket.js
  client/components/Itinerary.js
  client/components/LandingPage.js
  client/components/MapView.js
  client/components/ReservationForm.js
  client/components/ReservationRow.js
  client/components/TicketForm.js
  client/components/TicketFormContainer.js
  client/components/TicketList.js
  client/components/TicketRow.js
  client/components/TicketTable.js
  client/store/amenities.js
  client/store/campsite.js
  client/store/reservation.js
  client/store/reservations.js
  client/store/ticket.js
  client/store/ticketFormContainer.js
  script/seed.js
  server/api/campsites.js
  server/api/reservations.js
  server/db/models/reservation.js
  server/db/models/tests/amenity.spec.js
  server/db/models/tests/reservation.spec.js
Labels: in progress

#121 Navbar fix #117
  client/components/Camera.js
  client/components/Checkout.js
  client/components/HelpSubSuccess.js
  client/components/ReservationForm.js
  client/components/TicketForm.js
  client/components/navbar.js
  public/style.css
Labels: in progress

#122 Insights issue#107
  client/components/CampsiteTypeChart.js
  client/components/Insights.js
  client/components/PriorReservationsChart.js
  client/components/TopCampsitesThisWeek.js
  client/components/index.js
  client/components/user-home.js
  client/store/reservations.js
  client/utils/IntegerMonthTable.js
  client/utils/convertToChartData.js
  client/utils/getCampsiteTypeData.js
  client/utils/getPrevReservationData.js
  client/utils/getTopCampsitesWeek.js
  package-lock.json
  package.json
Labels: in progress

#124 Navbar fix #117
  client/components/CampsiteTypeChart.js
  client/components/Insights.js
  client/components/PriorReservationsChart.js
  client/components/TopCampsitesThisWeek.js
  client/components/navbar.js
  server/db/models/ticket.js
Labels: in progress

#125 Final styles #114
  client/components/AdminSidebar.js
  client/components/user-home.js
  client/store/analiticsToggle.js
  client/store/dashboard.js
  client/store/index.js
Labels: in progress

#126 Fix calendar bugs #93
  client/components/AdminCampsites.js
  client/components/Checkout.js
  client/components/Itinerary.js
  client/components/ReservationForm.js
  client/components/TicketList.js
  client/components/Type.js
  script/seed.js
  server/api/campers.js
  server/api/reservations.js
  server/db/models/reservation.js
Labels: needs review

#130 Fix admin sidebar #127
  client/components/AdminSidebar.js
  client/components/user-home.js
  client/store/analiticsToggle.js
  client/store/campersToggle.js
  client/store/campsitesToggle.js
  client/store/index.js
  client/store/reservationsToggle.js
  client/store/ticketsToggle.js
  server/api/reservations.js
Labels: needs review

#131 Navbar fix #117
  client/components/CampsiteTypeChart.js
  client/components/EditTicket.js
  client/components/Insights.js
  client/components/PriorReservationsChart.js
  client/components/TicketMapView.js
  client/components/TopCampsitesThisWeek.js
  client/components/index.js
  script/seed.js
  ticketSeedData.js
Labels: in progress

#132 routing fixes
  client/components/CamperProfile.js
  client/components/CamperRow.js
  client/components/user-home.js
  client/store/tickets.js
Labels: in progress

#133 Sidebar and routes
  client/components/AddCampsite.js
  client/components/AdminSidebar.js
  client/components/CamperRow.js
  client/components/EditCampsite.js
  client/components/TicketList.js
  client/components/TicketMapView.js
  client/components/TicketTable.js
  client/components/index.js
  client/components/user-home.js
  client/routes.js
  server/api/campsites.js
  server/db/models/index.js
Labels: in progress

#136 Searchbar modularity
  client/components/AdminCampsites.js
  client/components/CamperProfile.js
  client/components/CampersList.js
  client/components/CampersSearchBar.js
  client/components/LandingPage.js
  client/components/Reservations.js
  client/components/SearchBar.js
  client/components/TicketForm.js
  client/components/TicketList.js
  client/components/TicketTable.js
  client/components/user-home.js
  client/store/amenities.js
  client/store/campers.js
  client/store/campsites.js
  client/store/reservations.js
  client/store/tickets.js
  client/utils/doesSearchMatch.js
  client/utils/getSearchParams.js
  package.json
  server/api/campers.js
  server/api/campsites.js
  server/api/reservations.js
  server/api/tickets.js
  server/utils/camelCase.js
  server/utils/parseQueryToObject.js
Labels: in progress

#135 admin search module working, complete entity integration pending
  client/components/AdminCampsites.js
  client/components/Reservations.js
  client/components/SearchBar.js
  client/components/TicketList.js
  client/components/TicketTable.js
  client/components/user-home.js
  client/store/amenities.js
  client/store/reservations.js
  server/api/campsites.js
  server/api/reservations.js
Labels: needs review
